user:
  role:
    Developer
  password: "{cipher}AgDRD4BKKOG5QZgbwFEtBAQWofQ5+bHjE6W+Jj8Mzn0H/CVPTOFizBRMbUsc3kdCA8HUrRpCbypQaoEuJEqVyTwPXfM/PBjD0b8OaCHI5uIN1MKXrH2RFlVn28SR0/9XcpGvceMhf2yQEyugjs4gzYuM0XxQgwb/k1USPpKpfdjLLeGZGyY95H7QNqnxocyojUTjqe2cdqYInLAF0VsuvRlwwe6Scj4wNhJzQBs6XHc6YVbmZgphFzZJrJXIuLhqJqKyq+JdaVaLXbLOyp2dHlzbnSt2h/PzmD33wZSqPjf1AoJN0Ib3DkZr8J9uuoZC5DRPj9H/q5DEglY5u+JoD1o2nSdlziOln65gcwd7I3HLKB21K5KJrvzZ2/beh2m0laHH6bTfVTP+QyR95Ahxos2FHtzuxGmPzun8MjKGcQFmdXwZvZr272jaMUqn3dJqV/0PUZg8yG03REBGC2LWlKuDY7tTYGBrowntmJlRnYwqWQQrkeb/4YUJ3Bt91hV8oTr498vxL8jEgWs1SlmZ72epPkZLRpa9HIooIac90BHiZGHuM0RU3u2SPV4gDPJmf5D36RuqGrAXpLeFMdbGzoZRQJWYH+oMAYHbBPr+aTdHdafi/vOiVzWyiWwQ0zy4S+o54XQlQ1ZVDwyBj7j8ASdNv721gp87my+CB7L5SEXSwVLHg/E/kp/K2RGTKiHn9qvhtsHsIBXlhbhWsGFZaGLC"

message: fuck all of you12

